#! /usr/bin/env python
import sys
sys.path.insert(0, 'bin/')

import socket, sys
from drinkz.app import SimpleApp
from wsgiref.simple_server import make_server


def main(args):
	if len(args) != 3:
		print "Error, not enough args"
	else:
		s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)

		host = str(args[1])
		port = int(args[2])
			
		try:
			address = socket.gethostbyname(host);
		except socket.gaierror:
			print "Nope"
			return 0

		s.connect((host,port))
		s.send("GET / HTTP/1.0\r\n\r\n")

		while 1:
			buf = s.recv(1000)
			if not buf:
				break
			sys.stdout.write(buf)
		#waits inf for response i think... why no response?

		#print buf

if __name__ == '__main__':
   exit_code = main(sys.argv)
   sys.exit(exit_code)