#! /usr/bin/env python
import sys
sys.path.insert(0, 'bin/')

import socket, sys
from drinkz.app import SimpleApp
from wsgiref.simple_server import make_server


def main(args):
	if len(args) != 3:
		print "Error, not enough args"
	else:
		s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)

		app = SimpleApp()
		print "host: ", args[1]
		print "port: ", args[2]

		host = str(args[1])
		port = int(args[2])
		    
		httpd = make_server('', port, app)
		

		connection = "http://%s:%d/" % (host, port)
		print connection

		try:
			address = socket.getfqdn();
		except socket.gaierror:
			print "Nope"
			return 0

		s.connect((host,port))
		httpd.serve_forever()
		s.send("GET / HTTP/1.0")
		print "here"

		buf = s.recv(1000)
		print "there"
		print buf
			
		s.close()

if __name__ == '__main__':
   exit_code = main(sys.argv)
   sys.exit(exit_code)